<?
	$PLAN_SAVE = $this->PLAN_SAVE;
	$PLAN_OPTION_SAVE = $this->PLAN_OPTION_SAVE;
	$ARR_ROOM = $this->ARR_ROOM;
	$ARR_PROJECT_ROOM = $this->ARR_PROJECT_ROOM;
	$projectData = $this->projectData;//заказ
	$starting_price = $this->starting_price;//цена
	$step = $this->step;
	$nextstep = $this->nextstep;
	$nextstep_d = $this->nextstep_d;
	$url = $this->url;
	$cityModel    = new Sibirix_Model_City();
	$item_save = $this->item_save;
	$access = $this->access;
	$auth = $this->auth;
	$total_area = 0;
	
	foreach($ARR_PROJECT_ROOM as $room){
		$total_area+=$room->PROPERTY_AREA_VALUE;
	}
	
?>



<input type="hidden" id="designId" name="designId" value="2475">
<div id="service-page">
	<div class="head">
		<div class="content-container">
			<div class="content">
				<h2 class="main-title">Создание проекта</h2>
				<div id="service_menu">
					<ul>
						<li><a class="under-link" href="/project/step1/">Выбор планировки</a></li>
						<li><a class="under-link" href="/project/step2/">Параметры дизайн-проекта</a></li>
						<li class="selected"><a href="/project/step3/">Оформление</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
		<div class="content-container">
			<div class="left_bn">
				<div class="content">
					<h2 class="page-title">Проверка заказа</h2>
					<p class="title_type4">Общая площадь <?=$total_area?>м&#178;</p>
					<ul class="list-room">
					<?foreach($ARR_PROJECT_ROOM as $room){?>
						<li><?=$room->PROPERTY_TYPE_ROOM?><span class="point">......................</span><?=$room->PROPERTY_AREA_VALUE?>м&#178;</li>
					<?}?>
					</ul>
					<hr/>
					<p class="title_type4">Планировка</p>
						<div class="plan" style="position:relative"><img src="<?=$PLAN_OPTION_SAVE[0]->PLAN_IMAGE?>" alt="">
						</div>
					<hr/>
					
					<p class="title_type4">Комнаты</p>
					
			
			<?
			$i = 1;
			foreach($ARR_PROJECT_ROOM as $room){
				
				if($i == 1){
					$class = "open";
				}
				else{
					$class = "closeroom";
				}
			?>	
			<div class="open-close-room js-close-open-room <?=$class?>" data-for="room_n_<?=$i?>"><span class="status"></span><span class="room_txt">Комната №<?=$i?>(<?=$room->PROPERTY_AREA_VALUE?>м&#178;)</span><span class="arrow"></span></div>
			<div class="room_option <?=$class?>" id="room_n_<?=$i?>">
				<form enctype="application/x-www-form-urlencoded" class="js-family-form" action="/project/savestep4" method="post" novalidate="novalidate">				
						<div class="row row_popup">
							<div class="col-xs-6 col-sm-6 col-md-6">
								<label class="type_family">Взрослые</label>
								<div class="list-item-family">
									<?
									foreach($room->PROPERTY_PEOPLE_VALUE as $people){
						
										?>
										<div class="item-family">
											<span class="icon_family"></span>
											<div class="select2_view_n1">
												<div class="select2-container select-container-age-1" style="position:relative">
													<label>Возраст</label>
														<div class="value_popups"><?=$people?></div>
												</div>
											</div>
										</div>
									<?}?>
								</div>
							</div>
							<div class="col-xs-6 col-sm-6 col-md-6">
							<label class="type_family">Дети до 18</label>
							<div class="list-item-family">
									<?
									foreach($room->PROPERTY_PEOPLE_CHILDREN_VALUE as $people){
						
										?>
										<div class="item-family">
											<span class="icon_family"></span>
											<div class="select2_view_n1">
												<div class="select2-container select-container-age-1" style="position:relative">
													<label>Возраст</label>
														<div class="value_popups"><?=$people?></div>
												</div>
											</div>
										</div>
									<?}?>
								</div>
							</div>
						</div>
						<?if(count($room->PROPERTY_DESIGN_LIKED_VALUE) > 0){?>
						<div class="row">
							<label class="type_family">Понравившиеся дизайны</label>
							<div class="list-like-design">
								<ul>
								<?	foreach($room->PROPERTY_DESIGN_LIKED_VALUE as $design){?>
										<li class="design"><img src="<?=$design?>" alt=""/></li>
								<?}?>
								</ul>
							</div>
							<div class="clear"></div>
						</div>
						<?}?>
						<div class="row row_popup">
							<div class="col-xs-6 col-sm-6 col-md-6">
								<label class="type_family">Стоимость</label>
								<div class="data-room">
									<span class="font-type-4"><?=$room->PRICE_ROOM?> ₽</span><span class="formula">(300 ₽ × 76 м2) + 850 ₽<br/>
																	(20% комиссия за пользованием системы)</span>
								</div>
							</div>
							<div class="col-xs-6 col-sm-6 col-md-6">
								<div style="float:right;">
									<label class="type_family">Срок</label>
									<div class="data-room">
										<span class="font-type-4"><?=$room->PROPERTY_TIME?></span>
									</div>
								</div>
							</div>
							<div class="clear"></div>
						</div>
						<?if(!empty($room->PROPERTY_SUGGEST['TEXT'])){?>
							<div class="row row_popup">
									<label class="type_family">Описание проекта</label>
									<?=$room->PROPERTY_SUGGEST['TEXT']?>

								</p>
							</div>
						<?}?>

	
				
					<input type="hidden" name="protect" value="proomer-i-am-not-bot" class="js-protect" id="protect">
					<!--<div class="step active" id="deneg_day">
						<a id="nextstep" class="js-submit btn">Перейти к оплате</a>
					</div>-->				
				</form>
			</div>
			<?
			$i+=1;
			}?>		
					
					
					
					
					
					
					
					
					
					
					
					
					
					
					
					
					
					
					
					
					
					
					
					
					
					
					
					
				<div class="project_step3_btn">
					<div class="btn-wrapper-dropdown">
						<a class="btn blue waves-effect to-basket basket js-add-basket" href="javascript:void(0)" data-element-id="<?=$projectData->ID?>">Подтвердить</a>
					</div>
					<div class="btn-wrapper-dropdown">
						<a class="btn no-ph waves-effect" href="/project/step2/">Редактировать</a>
					</div>
				</div>
				</div>
			</div>
			<div class="right_bn">
			<?= $this->partial('project/partials/right_bn.phtml', array('noshow' => true, 'access' => $access, 'auth' => $auth, 'starting_price' => $starting_price, 'projectData' => $projectData, 'url' => $url, 'nextstep' => $nextstep, 'nextstep_d' => $nextstep_d, 'PLAN_SAVE' => $PLAN_SAVE, 'PLAN_OPTION_SAVE' => $PLAN_OPTION_SAVE)) ?>
		</div>
			<div class="clear"></div>
		</div>
</div>
<script>
	//Времмено находится тут
	(function(){
		var a = document.querySelector('.right_bn'), b = null, P = 10;
		window.addEventListener('scroll', Ascroll, false);
		document.body.addEventListener('scroll', Ascroll, false);
		function Ascroll() {
		  if (b == null) {
			var Sa = getComputedStyle(a, ''), s = '';
			for (var i = 0; i < Sa.length; i++) {
			  if (Sa[i].indexOf('overflow') == 0 || Sa[i].indexOf('padding') == 0 || Sa[i].indexOf('border') == 0 || Sa[i].indexOf('outline') == 0 || Sa[i].indexOf('box-shadow') == 0 || Sa[i].indexOf('background') == 0) {
				s += Sa[i] + ': ' +Sa.getPropertyValue(Sa[i]) + '; '
			  }
			}
			b = document.createElement('div');
			b.style.cssText = s + ' box-sizing: border-box; width: ' + a.offsetWidth + 'px;';
			a.insertBefore(b, a.firstChild);
			var l = a.childNodes.length;
			for (var i = 1; i < l; i++) {
			  b.appendChild(a.childNodes[1]);
			}
			a.style.height = b.getBoundingClientRect().height + 'px';
			a.style.padding = '0';
			a.style.border = '0';
		  }
		  var Ra = a.getBoundingClientRect(),
			  R = Math.round(Ra.top + b.getBoundingClientRect().height - document.querySelector('footer').getBoundingClientRect().top);  // селектор блока, при достижении нижнего края которого нужно открепить прилипающий элемент
		  if ((Ra.top - P) <= 0) {
			if ((Ra.top - P) <= R) {
			  b.className = 'stop';
			  b.style.top = - R +'px';
			} else {
			  b.className = 'sticky';
			  b.style.top = P + 'px';
			}
		  } else {
			b.className = '';
			b.style.top = '';
		  }
		  window.addEventListener('resize', function() {
			a.children[0].style.width = getComputedStyle(a, '').width
		  }, false);
		}
})()	
</script>
