<?= $this->form ?>
<script src="http://malsup.github.com/jquery.form.js"></script>
<script>
    // wait for the DOM to be loaded
    $(document).ready(function() {
        // bind 'myForm' and provide a simple callback function
        $('form').ajaxForm(function(data) {
            if (!$.isArray(data.form)) {
                alert('error');
                console.log(data);
            } else {
                alert('ok');
            }
        });
    });
</script>
