<?

	$itemList = $this->itemList;
	$PLAN_SAVE = $this->PLAN_SAVE;
	$PLAN_OPTION_SAVE = $this->PLAN_OPTION_SAVE;
	$projectData = $this->projectData;
	$starting_price = $this->starting_price;
	$step = $this->step;
	$nextstep = $this->nextstep;
	$url = $this->url;
	$nextstep_d = $this->nextstep_d;
	$uploadItemList = $this->uploadItemList;
	$step = $this->step;
	$cityModel    = new Sibirix_Model_City();
	$nextstepfile = true;
	$PLAN_ARR = $this->PLAN_ARR;
	$auth = $this->auth;
	$access = $this->access;
?>
						<?= $this->render('plan/apartment.ajax.phtml') ?>
