<div class="content">
<div class="executor-block">
    <div class="content-container">
        <h2 class="executor-title">Найдите исполнителя в два клика<br/>
с помощью Proomer.ru<a href="" class="blue">(Придумать)</a></h2>
        <div class="subtitle">Уже стали счастливым собственником жилья или только присматриваетесь к будущей квартире?<br/> Посмотрите идеи для своего интерьера.</div>
            <table width="100%" class="executor-list">
				<thead>
					<tr>
						<th>Название проекта</th>
						<th>Планировка</th>
						<th>Стоимость</th>
						<th>Откликов</th>
						<th>Срок</th>
					</tr>
				</thead>
				<tbody>
	<tr>
	<td class="name">
	<h2 class="title"><a href="" class="under-link">Выполнить ремонт 2-х комн. квартиры. Смету вышлю исполнителю</a></h2>
	<p class="disc">Выполнить ремонт 2-х комн. квартиры. Смету вышлю исполнителю
	пример оформления второй строки</p>
	</td>
	<td class="plan"><img src="/local/images/тест19.png"/></td>
	<td class="price">99999 Р</td>
	<td class="res">999 Р</td>
	<td class="time">99 лет</td>
	</tr>
						<tr>
					<td class="name">
						<h2 class="title"><a href="" class="under-link">Выполнить ремонт 2-х комн. квартиры. Смету вышлю исполнителю</a></h2>
						<p class="disc">Выполнить ремонт 2-х комн. квартиры. Смету вышлю исполнителю
пример оформления второй строки</p>
					</td>
					<td class="plan"><img src="/local/images/тест19.png"/></td>
					<td class="price">99999 ₽</td>
					<td class="res">999 </td>
					<td class="time">99 лет</td>
					</tr>

										<tr>
					<td class="name">
						<h2 class="title"><a href="" class="under-link">Выполнить ремонт 2-х комн. квартиры. Смету вышлю исполнителю</a></h2>
						<p class="disc">Выполнить ремонт 2-х комн. квартиры. Смету вышлю исполнителю
пример оформления второй строки</p>
					</td>
					<td class="plan"><img src="/local/images/тест19.png"/></td>
					<td class="price">99999 ₽</td>
					<td class="res">999 </td>
					<td class="time">99 лет</td>
					</tr>
										<tr>
					<td class="name"> 
						<h2 class="title"><a href="" class="under-link">Выполнить ремонт 2-х комн. квартиры. Смету вышлю исполнителю</a></h2>
						<p class="disc">Выполнить ремонт 2-х комн. квартиры. Смету вышлю исполнителю
пример оформления второй строки</p>
					</td>
					<td class="plan"><img src="/local/images/тест19.png"/></td>
					<td class="price">99999 ₽</td>
					<td class="res">999 </td>
					<td class="time">99 лет</td>
					</tr>
				</tbody>
			</table>
		<div class="clear"></div>
        <div class="btn-wrapper">
            <a href="/404/" class="btn blue waves-effect view_n3">Смотреть все проекты</a>
        </div>
    </div>
</div>
</div>